package co.com.uniandes.sube.parsistence;

import co.com.uniandes.arquitectura.jdbc.connection.DoctorRepository;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	
    public boolean someLibraryMethod() {
    	DoctorRepository r = new DoctorRepository();
        return true;
    }
}
